-- todo_items table seeds here (Example)
-- INSERT INTO todo_items (name, is_completed, category_id, user_id)
-- VALUES
-- ('Joker', false, 1, 1),
-- ('Arrival', false, 2, 1),
-- ('Bohemian Rapsody', false, 1, 1),
-- ('The Avatar', false, 1, 1),
-- ('Batman', false, 1, 1),
-- ('Avengers: Endgame', false, 1, 1),
-- ('The Hangover', false, 1, 1),
-- ('Arrival', false, 1, 1),
-- ('Bohemian Rapsody', false, 1, 1);
